springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

spring:
  application:
    name: small-authorizer
  datasource:
    username: root
    url: jdbc:postgresql://localhost:5432/account
    password: root
  jpa:
    database: POSTGRESQL
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  database:
    driverClassName: org.postgresql.Driver